language: node_js
node_js:
    - "node"
branches:
    only:
        - development
cache:
    directories:
        - "node_modules"
before_install:
    - npm i -g npm@latest
install:
    - npm install
script:
    - npm test
after_success:
    - npm run coverage
